name: profile-tiles-demo-build

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Go Version
        uses: actions/setup-go@v4
        with: 
          go-version: '1.20'
      - name: Build index.html
        run: |
          go build .
          ./profile-tiles
          mkdir page
          cp -R resources/ page/
          cp index.html page/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with: 
          path: ./page
  deploy:
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
